### PR TITLE
Run ci pipeline on pull request

### PR DESCRIPTION
**Pull request by arturo-seijas**

### CODE REVIEW

**Review by simskij — COMMENTED** [review]
While this works, it has the downside of making the connection between the `on_*.yaml` files and `ci.yaml` a bit opaque. For instance, using the "Show workflow file" feature of the actions UI will only show the stub file that calls out to `ci.yaml`.

I personally prefer either keeping it in a single file or duplicating the content into two files for that reason, even if it might be considered less DRY.

@DomFleischmann @jnsgruk @gruyaume What do the rest of you think?

**Comment by DomFleischmann** [comment]
> @DomFleischmann @jnsgruk @gruyaume What do the rest of you think?

We have adopted a similar pattern as proposed in this PR in our repositories. The benefit we see from it is that it gives you a clearer view of when things are executed. Additionally it alows us to batch change these files in all our repositories  as `ci.yaml` is really the only file with repository specific logic. You can see an example of our structure [here](https://github.com/canonical/dex-auth-operator/tree/main/.github/workflows).

@arturo-seijas for future PRs it would be better to provide description with the reasoning of these changes.

**Comment by jnsgruk** [comment]
Yeh, this does feel sensible enough to me. @simskij are you still opposed?

**Comment by simskij** [comment]
It seems like incidental duplication to me, and somewhat works against the UI, but I don't feel strongly enough about it to push it :) Let's merge it then! 🎉 Thank you @arturo-seijas for the contribution!

**Pull request merged**
