### PR TITLE
New charmcraft init templates

### PR DESCRIPTION
**Pull request by jnsgruk**
**DO NOT MERGE**

This PR serves as a reference/discussion point for @facundobatista and other stakeholders  to implement the new `charmcraft init` profiles.

I've added three templates to start, and I think we should keep the number relatively limited. I've added:

- `default` - similar to the current default template
- `kubernetes` - a minimal template using `tox` and `pyproject` with little boilerplate
- `machine` - as above, but for machine charms

Feedback welcome. At the very least, this is a starting point.

### CODE REVIEW

**Comment by jnsgruk** [comment]
FYI @sergiusens

**Review by simskij — COMMENTED** [review]
Two suggestions:

- Use tox in default as well. ~~Requires us to make an assumption what default means, but I guess at this point that it would still be a machine charm?~~ Could run whatever `run_test` is running from a tox env. Encourages consistency and good practices.
- Add a workflow to the repo that runs `on: create` which deletes the template folders, as well as itself, to not have the additional folders interfere with people using the template repo functionality.

**Comment by jnsgruk** [comment]
Not averse to having tox in the default template - seems like a reasonable idea

We don't need the other bit, as the charmcraft tool will sort that out. The profiles will be baked into charmcraft, so we'll stop using the GitHub template feature

**Comment by simskij** [comment]
> Not averse to having tox in the default template - seems like a reasonable idea
> 
> We don't need the other bit, as the charmcraft tool will sort that out. The profiles will be baked into charmcraft, so we'll stop using the GitHub template feature

Sure, I just assumed we wanted to allow both options 😅

**Comment by jnsgruk** [comment]
@simskij I've updated to include a CONTRIBUTING.md in each case, and also move the default to use tox and include integration tests.

**Comment by jnsgruk** [comment]
@facundobatista it strikes me that a lot of the files are the same for each template, so we probably want to find a way to deduplicate where we can in the actual implementation. Perhaps we have a set of "core files" (README, tox.ini, CONTRIBUTING, etc) that are present in every template, then a set of overlays that provide the charm/test files? Might make things easier to maintain and keep in sync.

**Comment by sergiusens** [comment]
a nice dedup strategy is to use symlinks and allows for proper forking of templates if necessary without adding complexity to how templates work.

**Review by simskij — APPROVED** [review]

**Pull request closed without merging**
